name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H 54.160.243.61 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ec2-user@54.160.243.61 "echo 'SSH connection successful'"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ec2-user@54.160.243.61 << 'EOF'
            cd /home/ec2-user/fastapi-book-project
            git pull origin main
            sudo yum install -y git
            sudo systemctl restart fastapi  # Update this with your actual service name
          EOF
